### ISSUE TITLE
Renaming `master` to `main`

### ISSUE THREAD

**Issue by jakirkham** [dask/community#68]
Would like to suggest we rename our branches from `master` to `main`. The term `master` can be problematic and is something even [GitHub themselves is moving away from]( https://www.businessinsider.com/github-replacing-software-code-terms-master-slave-2020-6?op=1 ). Suspect beyond doing the work itself, the change has minimal (if any) long term maintenance associated. Would be interested in hearing others thoughts on this 🙂

**Comment by TomAugspurger** [comment]
Some discussion on this for Python: https://discuss.python.org/t/communitys-take-on-changing-master-branch-to-main/4462

I'm in favor of changing this, but would happily let other projects move first and figure out what breaks :)

**Comment by jacobtomlinson** [comment]
I support terminology changes like this. Doing a quick search for terms like `whitelist` and `blacklist` and highlight a few things we should think about changing.

We recently had to resolve an issue where Bokeh renamed `whitelist` to `allowlist` in a non-backward compatible way. I propose we follow suit but perhaps consider making it backward compatible for a while to avoid breaking stuff for other folks.

**Comment by jsignell** [comment]
I agree that we should make this change. 

I don't love the idea of making the whitelist/allowlist change backwards compatible unless we have a very short and clearly defined timeline for getting rid of it entirely. Breaking some things might be considered part of the goal for this work.

**Comment by jacobtomlinson** [comment]
> Breaking some things might be considered part of the goal for this work.

Interesting I hadn't considered that.

**Comment by TomAugspurger** [comment]
There hasn't been any activity on
https://discuss.python.org/t/communitys-take-on-changing-master-branch-to-main/4462.
Does anyone know of other projects that have made the switch?

**Comment by jacobtomlinson** [comment]
Other discussions that I could find:

- [Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1643142)
- [Bokeh](https://github.com/bokeh/bokeh/issues/10224)
- [Scikit-learn](https://github.com/scikit-learn/scikit-learn/issues/17595)
- [Airflow](https://github.com/apache/airflow/issues/9351)
- [ Elasticsearch](https://github.com/elastic/ecs/issues/878)

Of those it seems only Mozilla has gone ahead with the change already.

**Comment by jsignell** [comment]
Definitely not the same as OSS but we made the change at Saturn and it was pretty seamless.

**Comment by TomAugspurger** [comment]
FYI: https://github.com/github/renaming/.

> If you haven’t moved yet, we recommend not moving right now, and waiting until later this year. We’re investing in tools to make the renaming the default branch of an existing repository a seamless experience for both maintainers and contributors.

**Comment by bryevdv** [comment]
FWIW we did just start this and things have been relatively painless.

**Comment by jacobtomlinson** [comment]
It was raised in dask/dask#6922 that there are other words such as `chain` that we may want to consider changing for similar reasons. Diverting that discussion here to be continued.

**Comment by jsignell** [comment]
I think Github has now implemented all the helper utils for migrating from master to main: https://github.com/github/renaming 

I am down to help with any work that this change would entail.

**Comment by jrbourbeau** [comment]
I'm also +1 for migrating to `main` and am around to help. Following up on https://github.com/dask/community/issues/68#issuecomment-680243312, is there any objection to trying this out on a smaller project first (e.g. `dask-examples`) as a test before moving onto repos like `dask` and `distributed` with more traffic? 

FWIW scikit-learn made the switch to `main` recently https://twitter.com/scikit_learn/status/1352677206972051456

**Comment by jacobtomlinson** [comment]
Would probably be good to track this for subprojects in the same way we are doing for the GitHub Actions migration.

_Also side note I wrote a [blog post](https://jacobtomlinson.dev/posts/2020/how-to-check-out-the-default-git-branch/) a while back that folks may find helpful on setting up aliases to check out and pull the default branch. I personally work on projects that use `master`, `main`, `gh-pages`, `next`, etc. So a smart alias is helpful._

**Comment by jsignell** [comment]
Progress:
- [ ] [dask/dask-examples](https://github.com/dask/dask-examples/issues/184)
- [ ] [dask/dask-cloudprovider](https://github.com/dask/dask-cloudprovider/issues/244)

**Comment by jacobtomlinson** [comment]
Quick FYI GitHub helpfully lets you know the default branch has changed and you need to run some commands to update your local clone.

However it doesn't mention that you need to head to your fork and rename the default branch there first otherwise those commands will fail.

![image](https://user-images.githubusercontent.com/1610850/106025059-502c4d00-60c0-11eb-8774-b8bc1d6e0e29.png)

**Comment by jrbourbeau** [comment]
[Almost all of the repos in the Dask org](https://github.com/dask/community/issues/68#issuecomment-768403970) have either made the migration from `master` -> `main` or have been archived. So far there haven't been any reported issues (that I'm aware of) as a result of the branch name change. Given this we're planning to move over `dask/dask` and `dask/distributed` soon. Just wanted to give folks tracking this issue a heads up

**Comment by jsignell** [comment]
@jacobtomlinson just found that read the docs caches the name of the default branch, so project maintainers may need to verify that the correct branch is being built. I am opening issues to track this now:

- [x] [dask/dask](https://github.com/dask/dask/issues/7361)
- [x] [dask/distributed](https://github.com/dask/distributed/issues/4577)
- [x] dask-jobqueue
- [x] dask-image
- [x] dask-stories
- [x] [dask/yarn](https://github.com/dask/dask-yarn/issues/141)
- [x] [dask/gcsfs](https://github.com/dask/gcsfs/issues/359)
- [x] [dask/gateway](https://github.com/dask/dask-gateway/issues/382)
- [x] [dask/s3fs](https://github.com/dask/s3fs/issues/436)
- [x] [dask/fastparquet](https://github.com/dask/fastparquet/issues/569)
- [x] [dask/glm](https://github.com/dask/dask-glm/issues/95) <-- archived repo
- [x] [dask/zict](https://github.com/dask/zict/issues/44)
- [x] [dask/partd](https://github.com/dask/partd/issues/47)
- [x] [dask/dask-ml-benchmarks](https://github.com/dask/dask-ml-benchmarks/issues/5) <-- archived repo
- [x] [dask/dask-mpi](https://github.com/dask/dask-mpi/issues/66)

**Comment by jsignell** [comment]
I'm not sure if marketing uses read the docs.

**Comment by jsignell** [comment]
Ok then I think the list I have above is complete

**Comment by jakirkham** [comment]
All branches listed have been updated.

Down to the RTD issues listed above. Only a couple people have permissions on those. Tried pinging for help.

**Comment by jakirkham** [comment]
Think only dask-glm remains. Suggesting archiving it ( https://github.com/dask/dask-glm/issues/99 ) as it appears inactive

Edit: This is now archived

**Comment by phobson** [comment]
@jakirkham we recently took ownership of crick from Jim. We should rename that too. I can lead that.

**Comment by jakirkham** [comment]
Renaming the branch is straightforward. Happy to do that

There seem to [only be a few references to `master` in the repo]( https://github.com/dask/crick/search?q=master ). Though those seem unrelated to the project itself. Please let me know if I'm missing anything

Edit: Went ahead and renamed the branch

**Comment by jakirkham** [comment]
Closing as completed
